---
title: "Pair Assignment 2: Maritime Policy Research Proposal"
author: "Björn Boening, Laurence Hendry, Cody Koebnick"
date: "20th October 2015"
output: 
  
  pdf_document:
    latex_engine: xelatex
    toc: yes
nocite: |
  @Mejia.2009
  @Beckman2002a
  @Casella2006
  @Daxecker2015
  @ElioMarchione2014
  @Granovetter1973
  @Greengard.2012
  @Grover2007
  @Hanson2010
  @Kaluza2010
  @Kiourktsoglou2012
  @Marchione2013
  @Mastrobuoni2014
  @Mejia.2009
  @Short.2008
  @Stomakhin.2011
  @Twyman-Ghoshal2014
  @Wang2013
  @Wang2013a
bibliography:
  - library.bib
---

## 1. Introduction: 
### A. Research Question

This research project will focus on maritime piracy. Maritime piracy has been in the media, especially with attention directed to the Horn of Africa. ATALANTA, the European Union's naval mission, patrolled along the coast of Somalia to combat maritime piracy and protect trading vessels against attacks.  As it seems, fading media attention does not presuppose a reduced danger of maritime piracy globally.

Whilst on the shores of Somalia the threat of piracy has declined, piracy is on the rise in other regions. Last year there have been 235 attempted and successful attacks on ships of which the vast majority occurred on Asian waters (Parameswaran, 2015). 

The idea for the paper is to research a model which can predict the type of the attack and also examine the development of piracy hotspots around the world over time. The analysis starts with a dataset which entails data on ship, type, geographical position, and time and severity of the attack. The time variables give us year, month, day, hour, and minute. Geographical position is calculated by longitude and latitude data. Moreover, we intend to use weather data to have one truly exogenous variable. Caution is warranted with regards to seasonal correlation of weather and its possible effects on the behavior of pirates.

Our yet provisionally research question regarding maritime priacy patterns is: 

1. Did global piracy attacks increasse? 

Piracy as an act of robbery or criminal violence against vessels is the key concept of our research project. The United Nations’ International Law Commission has described piracy as not only happening at High Sea, but also in the air. This project focuses solely on maritime piracy, and thus  takes into account vessels on water. The International Chamber of Commerce’s International Maritime Bureau (IMB) has defined in 1992 piracy as “the act of boarding any vessel with an intent to commit theft or any other crime, and with an intent or capacity to use force in furtherance of that act”. The United Nations Convention on the Law of the Sea (1982) has defined piracy as “any illegal acts of violence, detention, or any act of depredation’ committed for private ends, in a ship-to-ship conflict that occurs in the high 
seas.”

### B. Relevance of topic

The global shipping routes are highly important for trading. Even if piracy attacks so far were unable to stop global trade, they are a (potential) threat not only for the shipping crew but as well can bear high costs in case of ransom notes. The (cost intensive) deployment of international naval forces in Somalia shows how serious the threat is for some countries. Especially the high dependence of many countries for imports/exports of natural resources, say gas and oil, Creates a severe vulnerability among the industrialised countries.   

Building on the research question, this work will have to identify which policies have led to an increase or decrease in maritime piracy. For each country or region, the effects might differ and thus it is fair to distinguish between policies that generally impact on piracy, or special policies that only have an effect in their respective region. With this knowledge, we draw policy recommendations for further dealing with anti-piracy measures. 

This research project, however, is especially interesting, because it will develop a predictive model. Many researchers have described the changing nature of maritime piracy [@Twyman-Ghoshal2014], but only few left the framework of descriptive statistics so far. 

## 2. Literature Review & theoretical approach
### Literature on the Topic - Gaps in Literature

Gladly some researchers already compiled and described data about maritime piracy already. Hanson [@Hanson2010] from the Council on Foreign Relations, for instance, published a piece which describes the nature and severity of piracy within the recent decades. She concludes that global piracy has been rising over the last decades in total numbers. However, many authors agree that the deployment of naval forces has cut off this rising [@Hanson2010@Twyman-Ghoshal2014@Kiourktsoglou2012]. We conclude, that depending on the area and the pirates’ equipment the threat can be tackled by law enforcement. As deployment of naval police and military forces is rather expensive, the potential of prediction is very high. It could support law enforcement bodies to allocate their resources more efficiently and effectively.

So far some researchers examined patterns of piracy in order to predict hotspots [@Daxecker2015@Marchione2013]. We hope to add to this branch of research by firstly compiling most recent data available from the IMB. For instance the research conducted by [@Twyman-Ghoshal2014] only covers data from 2001 to 2010. We will clean and merge the recent data and provide a comprehensive dataset about piracy attacks from 1993 to 2015. As a complement, we add exogenous independent variables from global weather. Secondly, our project will use a quantitative model, which so far has never been applied in this branch. Our aim is to show how much potential lies in the available data beyond descriptive statistics. 

## 3. Methodological Approach
### A. How to Answer the Question

First, the original dataset has to be cleaned from missing values. Thus, the study can't use all observations given by the International Maritime Bureau. We will rather delete reported attacks with missing data on relevant independent variables. Then we can see how many observations we can still use for our model. Every observation will need to have detailed geographical positioning and time data. This is crucial for any predictive model. The qualitative aspect of this work will ask which policies determine piracy and which policies would be suitable to combat it, based on the information retrieved from the data set.

Second, the study analyzes the development of maritime piracy in different regions across the world. The question asked is according to which patterns maritime piracy develops. To find any increase or decrease of attacks is the first step. The analysis builds on that by asking which policies have led to an increase and respectively to a decrease.

Among other reasons, for instance socio-economic factors, piracy can be explained by variables describing the ship’s characteristics (for instance fully loaded with promising cargo), and presence of law enforcement [@Twyman-Ghoshal2014]. Beyond that, we assume that an attack will most likely occur when the level of law enforcement is low and bypassing ships 
can be easily spotted before they reach the actual location of the attack. These independent variables have to be created, given the geographical data provided in the data, e.g. distance to coast on the ship's route to the location of the attack. Furthermore we will have to distinguish between regional differences in the nature of maritime piracy. The techniques and severity of piracy differs considerably among the regions. Over years South East Asia was known as the hotspot for piracy, however, Somalia has developed as a dreaded and severe piracy hotspot in recent years.

### B. Which Data, Variables and Strategies will be used and why

We have time-series cross-sectional micro-level data from different sources. Since 1992 the IMB collects pirate attacks in its yearly reports with detailed information on the attack, the 
pirates and the vessel. Not at all time the quality is the same. A known shortcoming is the fact that the IMB only collects self-reported attacks, and especially in the early years of the their database many attacks were not reported. This has many reasons, as for example theft from a vessel lying in a harbor was not always considered piracy, or simply because of mistrust against local institutions. To get the best picture available, we add data from the U.S. National Geospatial Intelligence Agency, which compiles data from other sources as well. They collect reports from local institutions, news agencies, and other sources available. Nevertheless, our study is limited in predicting piracy attacks in general, as it can only use cases where an attack somehow was reported.

The concept of maritime piracy will be embedded in the wider framework of predictive modelling. It will be important to explain how the model is functioning. This will be rather a mathematical than a social scientist's task. The authors of this study deem it necessary since only an understanding of the statistical tools behind it will give the idea credential.

In academia there are a lot of studies on maritime piracy which engage with the topic from a qualitative security policy perspective, however few from a quantitative one. Twyman-Ghoshal et al [@Twyman-Ghoshal2014] have studied aggregated data from the International Maritime Bureau (IMB) and the US National Geospatial Intelligence Agency to analyze piracy attacks from 2001 to 2010. They identified piracy hotspots and certain patterns of piracy tactics. Africa and Asia seem to remain piracy hotspots. Lack of further regional differentiation does not allow to narrow down hotpots within Africa or Asia. As for the patterns of attacks they have identified seven distinct features of attacks: 

1. location at sea, 
2. time of the day, 
3. target vessel characteristics, 
4. pirate characteristics, 
5. pirate action characteristics, 
6. motivation for piracy, 
7. target vessel's response to piracy.

These features have been identified analyzing descriptive statistics on panel data. The results describe the ratio of attacks which display a certain pattern for each of the seven feature characteristics. For example, pirate actions were overwhelmingly characterized by boarding, and the ratio of boarding dropped to 50% after 2008. Firing weapons seems to be rare in pirate actions. Firing occurs more often if target vessel is in motion.
These seven characteristics can serve as a starting point for our predictive model. The paper asks what factors determine either the success or the type of action of a piracy attack. 
Our hypothesis assumes that the success of the attack is inversely related to speed and maneuver behavior of the target vessel, since pirates possibly can't engage in long distance open sea hunts as costs would outrun benefits.

To identify the type of an attack the analysis selects several predictors which could have an influence on the attack carried out. Amongst the possible factors determining the features of an attack on high sea are weather, longitude and latitude, time, and speed. However, a potential relation suffers from a false positive. Piracy behavior and the behavior of the target vessels might influence each other. More importantly, it might depend inherently on the weather. Thus, the analysis need more than the self-reported data from the International Maritime Bureau (IMB) on piracy attacks. Weather as a natural phenomenon is a truly exogenous variable. Weather data is most useful when temperature, rain fall, wind speed, and swell is measured.

Possible sources for weather data are the Texas A&M and University and the University of Washington. Both provide comprehensive data on global weather characteristics. 

\newpage
##Bibliography:

